// Plugin: productionize-nextjs-compose.
//
// The generation Implementation behind the Productionize Capability. It emits the
// app's CANONICAL production artifacts — the ones `forge deploy` (C7) rolls:
//   - a multi-stage Next.js `Dockerfile` (Next `output: 'standalone'` → a slim
//     runtime image with no build tooling) + its `.dockerignore`,
//   - `compose.prod.yaml` derived from the app's declared `infra` (postgres/redis,
//     P1) + `--host`: the Traefik ingress labels (host rule + the
//     `loadbalancer.healthcheck` C7 gates on), `stop_grace_period`, the `proxy`
//     network, the data-plane sidecar (C3/C4) wiring, and the DB service,
//   - `.env.prod.example`.
//
// It generates using the SAME conventions the deploy-compose-rollout Implementation
// relies on (the `proxy` network the old replica is drained out of, the container
// healthcheck the roll gates on, `stop_grace_period`), so what this emits is exactly
// what a start-first roll expects. Every function here is PURE (string in/out) so it
// is unit-testable with no Docker — the Capability does the file I/O.

import { forgeNextConfig } from '../../shared/next-config';
import { DEFAULT_LIGHT, DEFAULT_FONT, DEFAULT_RADIUS } from '../../shared/theme';
import {
  describeSecret,
  requirementLabel,
  secretInterpolation,
  type SecretSpec,
  AUTH_SESSION_SECRET_NAME,
  GOOGLE_SECRET_NAMES,
  EMAIL_SECRET_NAMES,
} from './secret-catalog';

export const IMPLEMENTATION = 'productionize-nextjs-compose';

// The per-app operator runbook filename (C13) — a generated checklist of exactly the
// secrets THIS app needs, alongside the commented `.env.prod.example`.
export const PROVISIONING_FILE = 'PROVISIONING.md';

// ---------------------------------------------------------------------------
// R1 — image pins must be digest-pinned (`ref@sha256:<64 hex>`), never `latest`.
// ---------------------------------------------------------------------------
const DIGEST_PIN = /@sha256:[0-9a-f]{64}$/;

export function isDigestPinned(ref: string): boolean {
  return DIGEST_PIN.test(ref.trim());
}

// Sanitize an app name to a Postgres-safe db identifier (matches provision).
export function dbNameFor(appName: string): string {
  return appName.replace(/[^a-z0-9_]/gi, '_');
}

// Normalize a readiness path to a leading-slash absolute path.
export function normalizeReadinessPath(p: string): string {
  const t = (p || '').trim() || '/api/health';
  return t.startsWith('/') ? t : `/${t}`;
}

// ---------------------------------------------------------------------------
// Next standalone Dockerfile + .dockerignore
// ---------------------------------------------------------------------------

export interface ProdDockerfileOptions {
  appName: string;
  port: number;
}

// Multi-stage Dockerfile that produces a slim runtime image from Next's
// `output: 'standalone'` build. Stages: deps (install) → build (`next build`) →
// runner (only the standalone server + static assets + public/, no build tooling,
// non-root). `mkdir -p public` guarantees the COPY works even when the app has no
// public/ directory.
export function generateProdDockerfile(opts: ProdDockerfileOptions): string {
  const { appName, port } = opts;
  return `# Generated by Forge — Productionize (productionize-nextjs-compose).
# Canonical production image for ${appName}. Slim multi-stage build from Next's
# \`output: 'standalone'\` — no build tooling ships in the runtime layer.
# Do not hand-edit; re-run \`forge productionize\` instead.
# syntax=docker/dockerfile:1

FROM node:22-bookworm-slim AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci || npm install

FROM node:22-bookworm-slim AS build
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# public/ may not exist in every app — guarantee it so the runner COPY resolves.
RUN mkdir -p public && npm run build

FROM node:22-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=${port}
ENV HOSTNAME=0.0.0.0
# Run as a non-root user.
RUN groupadd --system --gid 1001 nodejs \\
 && useradd --system --uid 1001 --gid nodejs nextjs
# Next standalone output: a minimal server + trimmed node_modules, plus assets.
COPY --from=build /app/public ./public
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
USER nextjs
EXPOSE ${port}
CMD ["node", "server.js"]
`;
}

// Slim build context for the production image build. Keeps build tooling, local
// state, generated compose files, and env files OUT of the image.
export function generateProdDockerignore(): string {
  return `# Generated by Forge — Productionize (productionize-nextjs-compose).
node_modules
.next
.git
npm-debug.log*
Dockerfile
.dockerignore
compose.yaml
compose.prod.yaml
.env
.env.local
.env.prod
.env.prod.example
.forge
README.md
PROVISIONING.md
`;
}

// ---------------------------------------------------------------------------
// next config — idempotently ensure `output: 'standalone'`
// ---------------------------------------------------------------------------

export interface StandalonePatchResult {
  content: string;
  changed: boolean;
  action: 'already-standalone' | 'injected' | 'unmanaged';
  warning?: string;
}

const STANDALONE_LINE = "  output: 'standalone',";

// A fresh Next config used when the app has no config file: standalone output (the
// slim image needs it) + the always-on C10 `/auth/*` data-plane rewrite (shared with
// the scaffold, so a from-scratch app matches a scaffolded one).
export function defaultNextConfig(): string {
  return forgeNextConfig({ standalone: true });
}

// Idempotently ensure `output: 'standalone'` in an existing Next config's TEXT.
// - Already declares any `output:` → left untouched (never clobber a hand value);
//   warns if it isn't 'standalone'.
// - Otherwise inject the line into the first recognizable config-object opener.
// - No recognizable object → return unmanaged + a warning (do not rewrite the file).
export function applyStandaloneOutput(text: string): StandalonePatchResult {
  const outputMatch = text.match(/output\s*:\s*['"]([^'"]+)['"]/);
  if (outputMatch) {
    const val = outputMatch[1];
    return {
      content: text,
      changed: false,
      action: 'already-standalone',
      ...(val === 'standalone'
        ? {}
        : {
            warning: `next config already sets output: '${val}' (not 'standalone') — left as-is; the standalone Dockerfile needs 'standalone'.`,
          }),
    };
  }
  const openers: RegExp[] = [
    /const\s+\w+\s*(?::\s*[^=]+)?=\s*\{/, // const nextConfig = {   /   const nextConfig: NextConfig = {
    /export\s+default\s*\{/, //             export default {
    /module\.exports\s*=\s*\{/, //          module.exports = {
    /defineConfig\s*\(\s*\{/, //            defineConfig({
  ];
  for (const re of openers) {
    const m = text.match(re);
    if (m && m.index !== undefined) {
      const insertAt = m.index + m[0].length;
      const content = text.slice(0, insertAt) + '\n' + STANDALONE_LINE + text.slice(insertAt);
      return { content, changed: true, action: 'injected' };
    }
  }
  return {
    content: text,
    changed: false,
    action: 'unmanaged',
    warning:
      "could not find a Next config object to set output: 'standalone' — add it manually so the standalone image builds.",
  };
}

// ---------------------------------------------------------------------------
// forge.theme.json — the app's declared C16 theme (scaffolded starter)
// ---------------------------------------------------------------------------

// A neutral starter theme committed at the app repo root. It reproduces the default
// look (so an un-edited app is unbranded-but-clean) while exposing the full editable
// token surface: display name, mode, font, radius, and the color palette. Edit it to
// brand every platform-served page (auth + status) at once; add `logo`/`favicon` or a
// `custom_css` string (CSS only; sandboxed) for deeper control. Only scaffolded when
// absent — never clobbers an app's edited theme.
//
// `colors{}` is your palette for the chosen `mode`: with `mode:'light'` or `'dark'`
// pinned, `colors{}` is the WHOLE palette for that mode (surfaces included) — no
// `dark{}` block needed. Add a `dark{}` block only for `mode:'auto'` (where `colors{}`
// is the light palette and `dark{}` supplies the dark overrides).
export function generateStarterTheme(appName: string): string {
  const starter = {
    name: appName,
    mode: 'auto',
    font: DEFAULT_FONT,
    radius: DEFAULT_RADIUS,
    colors: { ...DEFAULT_LIGHT },
  };
  return JSON.stringify(starter, null, 2) + '\n';
}

// ---------------------------------------------------------------------------
// compose.prod.yaml — the canonical production stack `forge deploy` rolls
// ---------------------------------------------------------------------------

export interface ProdComposeOptions {
  appName: string;
  port: number;
  host: string;
  readinessPath: string;
  webImage: string; // digest-pinned (R1)
  dataPlaneImage: string; // digest-pinned (R1)
  withPostgres: boolean;
  withRedis: boolean;
  secrets: string[];
  certResolver: string;
  // The app declares scheduled jobs (a `forge.jobs.json` at the repo root). When set,
  // the compose bind-mounts that file into the data-plane sidecar and pins
  // FORGE_JOBS_FILE at it, so C2 registers the jobs on boot (P7.3).
  withJobs?: boolean;
  // The app declares a theme (`forge.theme.json`, C16). When set, the compose mounts
  // it into the data-plane sidecar and pins FORGE_THEME_FILE, so the hosted auth +
  // status pages render branded in production.
  withTheme?: boolean;
  // P26 — platform storage on Postgres. When set, the sidecar gets FORGE_STORE_BACKEND=postgres +
  // FORGE_DB_URL pointing at a SEPARATE `forge_platform` database with its own least-privilege role
  // (co-located on the app's Postgres instance, or a dedicated one when the app has no DB of its own).
  // The sidecar depends on Postgres being healthy. See docs/architecture/08-storage-strategy.md §6.
  platformDb?: boolean;
  // P33 — the blob (C20) backend: 'filesystem' (default; bytes on the durable forge_state volume) or
  // 's3' (bytes in an S3-compatible object store + metadata in Postgres). DECOUPLED from platformDb, so a
  // single-node Postgres deploy keeps blobs on the volume unless the app explicitly opts into S3. When
  // 's3', the sidecar gets FORGE_BLOBS_BACKEND=s3 and the operator supplies FORGE_S3_* in .env.prod.
  blobsBackend?: 'filesystem' | 's3';
  // Reverse-proxy network the old replica is drained out of on a roll (matches C7).
  proxyNet?: string;
  // C36 — MCP observability. When true, the web + data-plane services join the shared external
  // `observability` network and get the OTLP→Langfuse export env (endpoint + empty-default LANGFUSE
  // keys). The sidecar traces the MCP transport; the app continues the trace. Off by default.
  observability?: boolean;
}

// P34 — the OPTIONAL auth-provider vars the data-plane (which hosts C10 `/auth/*`) reads. When the app
// uses hosted auth they are wired into the sidecar env as defined-but-empty (`${NAME:-}`) even if not
// separately declared, so an operator fills them in .env.prod alone (the single source of truth) with no
// re-provision. Absence stays detectable (`GET /auth/config` reports google:false), never a crash.
const AUTH_PROVIDER_VARS = ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'SMTP_URL', 'EMAIL_FROM'] as const;
// The token the C2 scheduler presents on a cron fire and the app verifies. Its presence in the declared
// set marks an app "uses hosted auth" for the P34 wiring above.
const AUTH_SESSION_SECRET_VAR = 'AUTH_SESSION_SECRET';
const AUTH_SERVICE_TOKEN_VAR = 'AUTH_SERVICE_TOKEN';
// P36 — when the app declares scheduled jobs (`/api/cron/*`), the service token is DEPLOY-REQUIRED: the
// scheduler must present it and the app must verify it, else cron fires are bare unauthenticated POSTs to
// publicly-routed endpoints. Fail the deploy loudly (`${VAR:?…}`) when jobs are declared but it is unset.
const CRON_TOKEN_REQUIRED_REASON =
  'set AUTH_SERVICE_TOKEN in .env.prod — this app declares scheduled cron jobs (/api/cron/*); the C2 ' +
  'scheduler presents it on each fire and the app must verify it, else cron endpoints are publicly ' +
  'reachable and fire UNAUTHENTICATED (Traefik routes /api/* publicly)';

const DATA_PLANE_PORT = 3718;

// P26 — the platform datastore: a SEPARATE logical database + least-privilege role, NOT the app's DB.
// Isolation (a platform bug can't touch app tables and vice versa) + least privilege + independent
// migration ownership. Co-located on the app's Postgres instance by default (swap the URL to move it
// to a dedicated/managed instance later).
export const PLATFORM_DB_NAME = 'forge_platform';
export const PLATFORM_DB_ROLE = 'forge_platform';
// Generated init file mounted into the app's Postgres (`/docker-entrypoint-initdb.d/`) that creates the
// least-priv role + database on first init — only needed when the app ALSO has its own DB (role `forge`);
// when the app has no DB, the dedicated platform Postgres is initialized directly as this role/db by the
// image entrypoint (no file).
//
// P31 — this is a `.sql` file (run by the Postgres entrypoint via `psql -f`), NOT an executable `.sh`.
// A bind-mounted `.sh` in `/docker-entrypoint-initdb.d/` gets EXECUTED, and on Docker Desktop for Mac the
// mount is effectively noexec, so first boot dies with `bad interpreter: Permission denied` → the
// forge_platform role/db never get created → the data-plane crashes at `ensureIdentitySchema`. A `.sql`
// file is only READ by psql (no exec bit, no interpreter), so it works identically on Linux and macOS.
export const PLATFORM_DB_INIT_FILE = 'forge-platform-init.sql';

// The FORGE_DB_URL the sidecar dials — the platform role/db, password from .env.prod (never committed).
export function platformDbUrl(): string {
  return `postgres://${PLATFORM_DB_ROLE}:\${FORGE_PLATFORM_DB_PASSWORD:?set FORGE_PLATFORM_DB_PASSWORD in .env.prod}@postgres:5432/${PLATFORM_DB_NAME}`;
}

// First-init SQL: create the least-privilege platform role + its own database, idempotently. The password
// is read from the Postgres container env at init time via psql's backtick `\set` (kept out of the
// committed file) and safely quoted with `format(%L)`, so a special char in the password can't break the
// statement. The role is a plain LOGIN role that OWNS only `forge_platform` — no rights on the app's DB.
// P31 — a `.sql` file (psql `-f`), so it needs no exec bit and runs on Docker Desktop for Mac too.
export function generatePlatformDbInitSql(): string {
  return `-- Generated by Forge — Productionize (P26/P31). Creates the least-privilege platform datastore
-- role + database on first Postgres init. Runs ONLY on an empty data dir; for an existing volume, an
-- operator runs the equivalent SQL once. Do not hand-edit; re-run \`forge productionize\` instead.
\\set ON_ERROR_STOP on
-- Read the platform role password from the container env (injected via compose; never committed here).
\\set pw \`printf '%s' "$FORGE_PLATFORM_DB_PASSWORD"\`
-- Create the least-privilege LOGIN role, idempotently (%L safely quotes the password literal).
SELECT format('CREATE ROLE ${PLATFORM_DB_ROLE} LOGIN PASSWORD %L', :'pw')
  WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${PLATFORM_DB_ROLE}')\\gexec
-- Create its OWN database, owned by that role, idempotently.
SELECT 'CREATE DATABASE ${PLATFORM_DB_NAME} OWNER ${PLATFORM_DB_ROLE}'
  WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${PLATFORM_DB_NAME}')\\gexec
`;
}

// The canonical scheduled-jobs declaration file (C2) — a JSON array of jobs at the
// app repo root; the data-plane reads it (FORGE_JOBS_FILE) to auto-register on boot.
export const JOBS_FILE = 'forge.jobs.json';
// The app's declared theme (C16) — brands every platform-served page (auth + status).
// The data-plane reads it (FORGE_THEME_FILE) to render branded UI in production.
export const THEME_FILE = 'forge.theme.json';
// Where the sidecar reads the app's repo (FORGE_APP_REPO_PATH); the jobs/theme files mount here.
const APP_REPO_MOUNT = '/app';

// A container healthcheck (node fetch) — the roll (C7) gates on this container
// health before draining the old replica. Mirrors the runtime-docker-compose form.
function healthTest(url: string): string {
  return `["CMD", "node", "-e", "fetch('${url}').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]`;
}

export function generateProdCompose(opts: ProdComposeOptions): string {
  const {
    appName,
    port,
    host,
    readinessPath,
    webImage,
    dataPlaneImage,
    withPostgres,
    withRedis,
    secrets,
    certResolver,
  } = opts;
  const withJobs = opts.withJobs ?? false;
  const withTheme = opts.withTheme ?? false;
  const platformDb = opts.platformDb ?? false;
  // A postgres service exists if the app has its OWN database OR platform storage is on Postgres.
  const hasPostgres = withPostgres || platformDb;
  const proxyNet = opts.proxyNet ?? 'proxy';
  const db = dbNameFor(appName);
  const blobsBackend = opts.blobsBackend ?? 'filesystem';
  const observability = opts.observability ?? false;
  // C36 — the OTLP→Langfuse export env for a tier. The endpoint defaults to the internal Langfuse
  // address; the LANGFUSE keys are empty-default (`${VAR:-}`) so a missing key silently DISABLES tracing
  // (the tier is unaffected) instead of failing the deploy — observability must never take the app down.
  const otelEnv = (serviceName: string): string[] =>
    observability
      ? [
          '      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://langfuse-web:3000/api/public/otel}',
          `      - OTEL_SERVICE_NAME=${serviceName}`,
          '      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-}',
          '      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-}',
        ]
      : [];
  // Joins the web + sidecar to the shared external `observability` network (where the Langfuse stack
  // lives) + declares it at the bottom — only when observability is on.
  const observabilityNet = observability ? '\n      - observability' : '';
  const observabilityNetDecl = observability ? '\n  observability:\n    external: true' : '';
  // Traefik router/service keys must be a safe slug.
  const svc = appName.replace(/[^a-zA-Z0-9_-]/g, '-');

  // P34/P36 — the secret env lines shared by BOTH tiers. Each declared secret interpolates from .env.prod
  // (never a value in this file). P36: AUTH_SERVICE_TOKEN is forced DEPLOY-REQUIRED (`${VAR:?…}`) when the
  // app declares scheduled cron jobs, so an unset token fails the deploy loudly instead of firing bare,
  // unauthenticated POSTs at publicly-routed `/api/cron/*`.
  const usesAuth = secrets.includes(AUTH_SESSION_SECRET_VAR);
  const cronTokenInterp = `\${${AUTH_SERVICE_TOKEN_VAR}:?${CRON_TOKEN_REQUIRED_REASON}}`;
  const interpFor = (name: string): string =>
    withJobs && name === AUTH_SERVICE_TOKEN_VAR ? cronTokenInterp : secretInterpolation(name);
  const sharedSecretEnv: string[] = secrets.map((s) => `      - ${s}=${interpFor(s)}`);
  if (withJobs && !secrets.includes(AUTH_SERVICE_TOKEN_VAR)) {
    sharedSecretEnv.push(`      - ${AUTH_SERVICE_TOKEN_VAR}=${cronTokenInterp}`);
  }
  // P34 — the OPTIONAL auth-provider vars the data-plane reads (it hosts C10 /auth/*), wired ONLY into the
  // sidecar as defined-but-empty when the app uses hosted auth and hasn't already declared them, so an
  // operator enables Google/SMTP by filling .env.prod alone.
  const dpAuthProviderEnv: string[] = usesAuth
    ? AUTH_PROVIDER_VARS.filter((v) => !secrets.includes(v)).map((v) => `      - ${v}=\${${v}:-}`)
    : [];

  const dependsOn: string[] = [];
  if (hasPostgres) dependsOn.push('      postgres:\n        condition: service_healthy');
  dependsOn.push('      data-plane:\n        condition: service_started');

  // Web environment: prod NODE_ENV, the data-plane sidecar base URL, DB/Redis URLs
  // from infra, and one interpolation line per declared secret (`${NAME:-}` keeps it
  // defined-but-empty when unset, so the app degrades instead of crashing — EXCEPT a
  // deploy-required secret like AUTH_SESSION_SECRET, which the catalog emits as
  // `${NAME:?…}` so a missing/empty session-signing key FAILS the deploy loudly instead
  // of silently logging every user out. Real values come from .env.prod, never this
  // file). The data-plane base is published
  // under BOTH names: FORGE_EVENTS_URL is the contract the shipped C1/C3/C4 app
  // clients actually read; FORGE_DATA_PLANE_URL is kept as a compatible alias.
  const webEnv: string[] = [
    '      - NODE_ENV=production',
    `      - PORT=${port}`,
    '      - HOSTNAME=0.0.0.0',
    `      - FORGE_EVENTS_URL=http://data-plane:${DATA_PLANE_PORT}`,
    `      - FORGE_DATA_PLANE_URL=http://data-plane:${DATA_PLANE_PORT}`,
  ];
  if (withPostgres) {
    webEnv.push(
      `      - DATABASE_URL=postgres://forge:\${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env.prod}@postgres:5432/${db}`,
    );
  }
  if (withRedis) webEnv.push('      - REDIS_URL=redis://redis:6379');
  webEnv.push(...sharedSecretEnv);
  // C36 — the app tier emits the `app.mcp.dispatch` span (continues the transport trace).
  webEnv.push(...otelEnv(appName));

  // Traefik ingress: host rule + the loadbalancer healthcheck the roll relies on.
  const labels: string[] = [
    '      - "traefik.enable=true"',
    `      - "traefik.docker.network=${proxyNet}"`,
    `      - "traefik.http.routers.${svc}.rule=Host(\`${host}\`)"`,
    `      - "traefik.http.routers.${svc}.entrypoints=websecure"`,
    `      - "traefik.http.routers.${svc}.tls=true"`,
    `      - "traefik.http.routers.${svc}.tls.certresolver=${certResolver}"`,
    `      - "traefik.http.services.${svc}.loadbalancer.server.port=${port}"`,
    `      - "traefik.http.services.${svc}.loadbalancer.healthcheck.path=${readinessPath}"`,
    `      - "traefik.http.services.${svc}.loadbalancer.healthcheck.interval=10s"`,
  ];

  const web = `  web:
    image: ${webImage}
    restart: unless-stopped
    environment:
${webEnv.join('\n')}
    depends_on:
${dependsOn.join('\n')}
    networks:
      - ${proxyNet}
      - internal${observabilityNet}
    stop_grace_period: 30s
    healthcheck:
      test: ${healthTest(`http://localhost:${port}${readinessPath}`)}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    labels:
${labels.join('\n')}`;

  // The Forge data-plane sidecar (C3 app-event log + C4 notifications + C2
  // scheduler + C1 agent-run + C5 secrets read). The web app reaches it at
  // http://data-plane:3718 (FORGE_EVENTS_URL). Its store persists on a volume.
  //
  // Its DATA-plane capabilities run here, so it needs the same runtime injection the
  // web tier gets (P6): FORGE_SECRETS_KEY to DECRYPT the C5 vault at rest (on the
  // forge_state volume) + the declared secrets on the env (the process-env fallback
  // C1 agent-run reads when the vault is empty). Real values come from .env.prod.
  const dpEnv: string[] = [
    `      - PORT=${DATA_PLANE_PORT}`,
    `      - FORGE_APP_NAME=${appName}`,
    `      - FORGE_APP_REPO_PATH=${APP_REPO_MOUNT}`,
    '      - FORGE_STATE_DIR=/forge-state',
    // C5 vault master key — without it the sidecar can't decrypt secrets (C1 → 503).
    '      - FORGE_SECRETS_KEY=${FORGE_SECRETS_KEY:-}',
    // How the sidecar reaches the web tier over the internal network — the C2 scheduler
    // callback AND the C15 status page's live C6 health probe use these.
    '      - FORGE_APP_CALLBACK_HOST=web',
    `      - FORGE_APP_CALLBACK_PORT=${port}`,
    `      - FORGE_READINESS_PATH=${readinessPath}`,
  ];
  dpEnv.push(...sharedSecretEnv);
  // P34 — the optional Google/SMTP provider vars the sidecar reads for hosted auth (defined-but-empty
  // unless the operator fills .env.prod). Data-plane only — the web tier proxies /auth/* here.
  dpEnv.push(...dpAuthProviderEnv);
  // P38 — SPLIT-HOST auth public URL. The data-plane hosts C10 `/auth/*`, but it builds every auth URL
  // (the OAuth redirect_uri, the verify/reset links, and the post-login redirect) from `publicBase`, which
  // defaults to the host the request ARRIVED on. When the UI lives on a DIFFERENT public host than the API
  // (e.g. the web tier on app.<domain> proxying `/auth/*` to the platform on api.<domain>), that arrival
  // host is the API host — so a Google login callback + its host-only session cookie + the `/home` bounce
  // all land on the API host, stranding the user off the app. FORGE_AUTH_PUBLIC_URL pins the USER-FACING
  // origin (publicBase reads it FIRST); the data-plane only reads it, so we wire it defined-but-empty from
  // .env.prod for hosted-auth apps. Empty = today's request-host-derived behavior, so single-host apps are
  // unaffected. (Not on the web tier — it proxies `/auth/*` here and never computes an auth URL itself.)
  if (usesAuth) dpEnv.push('      - FORGE_AUTH_PUBLIC_URL=${FORGE_AUTH_PUBLIC_URL:-}');
  // P38 companion for the C24 CONNECTORS flow (`/connect/*`): its publicBase reads a SEPARATE var,
  // FORGE_OAUTH_PUBLIC_URL. Same split-host rationale — a "Connect Google" callback + its post-connect
  // `return_to` bounce (a relative path like /settings/integrations) must land on the USER-FACING host,
  // not the API host the proxied request arrived on. Wired defined-but-empty from .env.prod; empty =
  // request-host-derived (single-host apps unaffected). Data-plane only (the web tier proxies /connect/*).
  if (usesAuth) dpEnv.push('      - FORGE_OAUTH_PUBLIC_URL=${FORGE_OAUTH_PUBLIC_URL:-}');
  // C36 — the transport tier emits the `mcp.tool_call` trace ROOT (initOtelLangfuse reads these at boot).
  dpEnv.push(...otelEnv('forge-data-plane'));
  // The data-plane's ENTIRE state dir (FORGE_STATE_DIR=/forge-state) rides ONE durable
  // named volume. This is load-bearing for auth: C10's users/sessions/`forge_refresh`
  // records live at /forge-state/auth/<appId>.json, so the volume is what lets a signed-in
  // user SURVIVE a deploy — `forge deploy` recreates this sidecar onto the new pin, and a
  // named volume persists across that recreate (an ephemeral fs would wipe every session +
  // refresh token → 401 on /auth/session AND /auth/refresh → every user logged out). The
  // C5 secrets vault (/forge-state/secrets) rides the same volume, so its master key never
  // regenerates across a recreate either. Do NOT drop forge_state.
  const dpVolumes: string[] = ['      - forge_state:/forge-state'];
  if (withJobs) {
    // The app declares scheduled jobs — mount the declaration read-only and pin
    // FORGE_JOBS_FILE at it so C2 registers them on boot (P7.3). The registered
    // ScheduledJob state then persists on the forge_state volume.
    dpEnv.push(`      - FORGE_JOBS_FILE=${APP_REPO_MOUNT}/${JOBS_FILE}`);
    dpVolumes.push(`      - ./${JOBS_FILE}:${APP_REPO_MOUNT}/${JOBS_FILE}:ro`);
  } else {
    // No declared jobs — leave the seam optional so an operator can still point at one.
    dpEnv.push('      - FORGE_JOBS_FILE=${FORGE_JOBS_FILE:-}');
  }
  if (withTheme) {
    // The app declares a theme (C16) — mount it read-only and pin FORGE_THEME_FILE so
    // the hosted auth + status pages render branded in production.
    dpEnv.push(`      - FORGE_THEME_FILE=${APP_REPO_MOUNT}/${THEME_FILE}`);
    dpVolumes.push(`      - ./${THEME_FILE}:${APP_REPO_MOUNT}/${THEME_FILE}:ro`);
  } else {
    // No declared theme — the seam stays optional; pages fall back to the neutral default.
    dpEnv.push('      - FORGE_THEME_FILE=${FORGE_THEME_FILE:-}');
  }

  // P26 — platform storage on Postgres: select the backend + point the sidecar at the SEPARATE
  // forge_platform database, and make it wait for Postgres to be healthy (the sidecar fail-fasts on
  // an unreachable/misconfigured datastore at boot). Absent = the filesystem default (unchanged).
  const dpDependsOn: string[] = [];
  if (platformDb) {
    dpEnv.push('      - FORGE_STORE_BACKEND=postgres');
    dpEnv.push(`      - FORGE_DB_URL=${platformDbUrl()}`);
    dpDependsOn.push('      postgres:\n        condition: service_healthy');
  }
  // P33 — blobs (C20) ride the filesystem (forge_state volume) by DEFAULT, DECOUPLED from the structured
  // store above: a Postgres platform store no longer drags blobs onto S3. Only an explicit `blobsBackend:
  // 's3'` flips the sidecar to the object store (operator supplies FORGE_S3_* in .env.prod).
  if (blobsBackend === 's3') {
    dpEnv.push('      - FORGE_BLOBS_BACKEND=s3');
    for (const v of ['FORGE_S3_ENDPOINT', 'FORGE_S3_BUCKET', 'FORGE_S3_ACCESS_KEY', 'FORGE_S3_SECRET_KEY', 'FORGE_S3_REGION']) {
      dpEnv.push(`      - ${v}=\${${v}:-}`);
    }
  }
  const dpDependsBlock = dpDependsOn.length ? `\n    depends_on:\n${dpDependsOn.join('\n')}` : '';

  const dataPlane = `  data-plane:
    image: ${dataPlaneImage}
    restart: unless-stopped${dpDependsBlock}
    environment:
${dpEnv.join('\n')}
    volumes:
${dpVolumes.join('\n')}
    networks:
      - internal${observabilityNet}
    stop_grace_period: 15s
    healthcheck:
      test: ${healthTest(`http://localhost:${DATA_PLANE_PORT}/health`)}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s`;

  const services: string[] = [web, dataPlane];
  const volumes: string[] = ['  forge_state:'];

  if (hasPostgres) {
    if (withPostgres) {
      // The app has its OWN database (role `forge`, db `${db}`). When platform storage ALSO rides
      // Postgres, inject the platform password + mount the first-init script that creates the SEPARATE
      // least-privilege forge_platform role + database on the same instance (isolation + least priv).
      const pgEnv = [
        '      - POSTGRES_USER=forge',
        '      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env.prod}',
        `      - POSTGRES_DB=${db}`,
      ];
      const pgVolumes = ['      - postgres_data:/var/lib/postgresql/data'];
      if (platformDb) {
        pgEnv.push('      - FORGE_PLATFORM_DB_PASSWORD=${FORGE_PLATFORM_DB_PASSWORD:?set FORGE_PLATFORM_DB_PASSWORD in .env.prod}');
        pgVolumes.push(`      - ./${PLATFORM_DB_INIT_FILE}:/docker-entrypoint-initdb.d/${PLATFORM_DB_INIT_FILE}:ro`);
      }
      services.push(`  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
${pgEnv.join('\n')}
    volumes:
${pgVolumes.join('\n')}
    networks:
      - internal
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forge -d ${db}"]
      interval: 10s
      timeout: 5s
      retries: 5`);
    } else {
      // App has NO database of its own — a DEDICATED Postgres for platform state, initialized directly
      // as the forge_platform role/db by the image entrypoint (no init script needed).
      services.push(`  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${PLATFORM_DB_ROLE}
      - POSTGRES_PASSWORD=\${FORGE_PLATFORM_DB_PASSWORD:?set FORGE_PLATFORM_DB_PASSWORD in .env.prod}
      - POSTGRES_DB=${PLATFORM_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PLATFORM_DB_ROLE} -d ${PLATFORM_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5`);
    }
    volumes.push('  postgres_data:');
  }

  if (withRedis) {
    services.push(`  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - internal
    stop_grace_period: 10s
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5`);
  }

  return `# Generated by Forge — Productionize (productionize-nextjs-compose).
# The CANONICAL production stack — exactly what \`forge deploy\` rolls (start-first,
# behind Traefik on the "${proxyNet}" network). Do not hand-edit service topology;
# re-run \`forge productionize\` instead. Secrets/passwords come from .env.prod
# (see .env.prod.example) and are NEVER committed here. Images are digest-pinned (R1).
name: forge-${appName}-prod

networks:
  ${proxyNet}:
    external: true
  internal:
    driver: bridge${observabilityNetDecl}

services:
${services.join('\n\n')}

volumes:
${volumes.join('\n')}
`;
}

// ---------------------------------------------------------------------------
// .env.prod.example — documents the values .env.prod must supply
// ---------------------------------------------------------------------------

export interface EnvProdExampleOptions {
  appName: string;
  host: string;
  withPostgres: boolean;
  withRedis: boolean;
  secrets: string[];
  // The app declares scheduled jobs (forge.jobs.json) — the compose wires them
  // automatically, so the example documents that instead of the optional seam.
  withJobs?: boolean;
  // P26 — platform storage on Postgres: document the separate forge_platform DB password.
  platformDb?: boolean;
  // P33 — the C20 blob backend; when 's3', document the FORGE_S3_* the sidecar needs.
  blobsBackend?: 'filesystem' | 's3';
  // C36 — when observability is on, document the Langfuse OTLP key pair the compose references.
  observability?: boolean;
}

// The `#` comment block that precedes each secret in .env.prod.example — what it is,
// which capability needs it, required-vs-optional, how to obtain, how to generate.
// Catalog-driven (C13) so the operator never sees a bare, unexplained `NAME=`.
function envCommentLines(spec: SecretSpec): string[] {
  const lines = [
    `# ${spec.name} — ${spec.what}`,
    `#   ${spec.capability} · ${requirementLabel(spec)}. ${spec.requires_note}`,
    `#   Obtain: ${spec.obtain}`,
  ];
  if (spec.generate) lines.push(`#   Generate: ${spec.generate}`);
  return lines;
}

export function generateEnvProdExample(opts: EnvProdExampleOptions): string {
  const lines: string[] = [
    `# Generated by Forge — Productionize. Production config for ${opts.appName}.`,
    `# Copy to .env.prod, fill in real values, and DO NOT commit .env.prod.`,
    `# Consumed at deploy time (e.g. \`docker compose -f compose.prod.yaml --env-file .env.prod ...\`).`,
    `# Public host (baked into compose.prod.yaml Traefik labels): ${opts.host}`,
    `# Full operator guide + how to obtain each value: ${PROVISIONING_FILE} (this app) and forge/PROVISIONING.md.`,
    '',
    '# --- Forge secrets vault master key (C5) ---',
    ...envCommentLines(describeSecret('FORGE_SECRETS_KEY')),
    'FORGE_SECRETS_KEY=change-me',
    '',
  ];
  if (opts.withPostgres) {
    lines.push('# --- Postgres (required when the app is provisioned with a database) ---');
    lines.push(...envCommentLines(describeSecret('POSTGRES_PASSWORD')));
    lines.push('POSTGRES_PASSWORD=change-me');
    lines.push('');
  }
  if (opts.platformDb) {
    lines.push('# --- Forge platform datastore on Postgres (P26) ---');
    lines.push(`# FORGE_PLATFORM_DB_PASSWORD — password for the least-privilege ${PLATFORM_DB_ROLE} role that owns`);
    lines.push(`#   the separate ${PLATFORM_DB_NAME} database (Forge's OWN state: C10 identity, …). NOT the app DB.`);
    lines.push('#   Required when platform storage is on Postgres. Generate: openssl rand -hex 32');
    lines.push('#   (URL-safe hex — it is interpolated into FORGE_DB_URL; a base64 `/ + =` would break the URL, P32.)');
    lines.push('FORGE_PLATFORM_DB_PASSWORD=change-me');
    lines.push('');
  }
  if (opts.secrets.length) {
    lines.push('# --- Declared secrets (injected into the web AND data-plane containers; never commit real values) ---');
    for (const s of opts.secrets) {
      lines.push(...envCommentLines(describeSecret(s)));
      lines.push(`${s}=`);
      lines.push('');
    }
  }
  // P34 — when the app uses C10 hosted auth, the OPTIONAL Google/SMTP provider vars are already wired into
  // the data-plane by productionize (defined-but-empty), so .env.prod is the single source of truth: fill a
  // value here and redeploy — no `--secret`/re-productionize needed. Only surfaced for vars not already
  // declared above (a declared one is documented in its own block).
  const usesAuth = opts.secrets.includes(AUTH_SESSION_SECRET_VAR);
  if (usesAuth) {
    const undeclared = AUTH_PROVIDER_VARS.filter((v) => !opts.secrets.includes(v));
    if (undeclared.length) {
      lines.push('# --- Optional sign-in providers (C10) — wired into the data-plane; fill to enable, leave blank to skip ---');
      lines.push('# At least ONE sign-in method (Google OR SMTP) must be configured or no one can sign in.');
      for (const v of undeclared) {
        lines.push(...envCommentLines(describeSecret(v)));
        lines.push(`${v}=`);
        lines.push('');
      }
    }
  }
  // P33 — the S3 object store for blobs (C20), only when the app opted in (--blobs-backend s3).
  if (opts.blobsBackend === 's3') {
    lines.push('# --- Blob object store (C20, S3-compatible) — required because blobs_backend=s3 (P33) ---');
    lines.push('# FORGE_S3_ENDPOINT — e.g. https://s3.us-east-1.amazonaws.com or a MinIO URL.');
    lines.push('# FORGE_S3_BUCKET — the bucket blob bytes are stored in (created on boot if absent).');
    lines.push('# FORGE_S3_ACCESS_KEY / FORGE_S3_SECRET_KEY — credentials; FORGE_S3_REGION (default us-east-1).');
    lines.push('FORGE_S3_ENDPOINT=');
    lines.push('FORGE_S3_BUCKET=');
    lines.push('FORGE_S3_ACCESS_KEY=');
    lines.push('FORGE_S3_SECRET_KEY=');
    lines.push('FORGE_S3_REGION=us-east-1');
    lines.push('');
  }
  // C36 — MCP observability: the OTLP key pair the app + sidecar authenticate their Langfuse push with.
  if (opts.observability) {
    lines.push('# --- MCP observability (C36) — traces the full MCP interaction to the self-hosted Langfuse ---');
    lines.push('# The forge sidecar (transport) + this app (dispatch) export OTLP spans to the shared');
    lines.push('# observability stack, stitched into ONE trace. These keys authenticate the OTLP push (the');
    lines.push('# Langfuse project public/secret key pair). EMPTY = tracing silently disabled (the app is');
    lines.push('# UNAFFECTED); fill them to enable. Source: the box observability stack .env.langfuse.');
    lines.push('# OTEL_EXPORTER_OTLP_ENDPOINT defaults to http://langfuse-web:3000/api/public/otel.');
    lines.push('LANGFUSE_PUBLIC_KEY=');
    lines.push('LANGFUSE_SECRET_KEY=');
    lines.push('');
  }
  if (opts.withJobs) {
    lines.push('# --- Scheduled jobs (C2) ---');
    lines.push(`# ${JOBS_FILE} is mounted into the data-plane sidecar and registered on boot — no env needed.`);
    // P36 — cron fires MUST be authenticated: the compose makes AUTH_SERVICE_TOKEN deploy-required when jobs
    // are declared (an unset token fails the deploy), and the app gates /api/cron/* on it.
    if (!opts.secrets.includes(AUTH_SERVICE_TOKEN_VAR)) {
      lines.push('# AUTH_SERVICE_TOKEN is REQUIRED (P36): the C2 scheduler presents it on each fire and the app');
      lines.push('#   verifies it — without it /api/cron/* is publicly reachable and fires UNAUTHENTICATED.');
      lines.push('#   Generate: openssl rand -hex 32');
      lines.push('AUTH_SERVICE_TOKEN=change-me');
      lines.push('');
    }
  } else {
    lines.push('# --- Optional: scheduled jobs (C2) the data-plane sidecar registers on boot ---');
    lines.push(`# Declare jobs in ${JOBS_FILE} at the repo root (re-run \`forge productionize\` to wire it), or:`);
    lines.push(`# FORGE_JOBS_FILE=/app/${JOBS_FILE}`);
  }
  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// PROVISIONING.md — the per-app operator runbook (C13)
// ---------------------------------------------------------------------------

export interface ProvisioningRunbookOptions {
  appName: string;
  host: string;
  withPostgres: boolean;
  secrets: string[];
  withJobs?: boolean;
}

// The exact commands to set one secret — the dev path (C5 vault, control plane) and
// the prod path (`.env.prod` + redeploy). Kept as a helper so every row is consistent.
function setCommandLines(appName: string, name: string): string[] {
  return [
    `- **Dev / control plane** (encrypted C5 vault): \`./forge secrets set --app ${appName} --name ${name} --from-env ${name}\``,
    `  (export \`${name}\` first, or use \`--value <v>\`; \`--from-env\` keeps it out of shell history).`,
    `- **Prod / deployed**: put \`${name}=<value>\` in \`app/.env.prod\`, then redeploy so it's injected: \`./forge deploy --app ${appName}\`.`,
  ];
}

// The subset of the matrix THIS app needs, in provisioning order: the C5 vault key,
// the DB password (if provisioned with a DB), then every declared secret. P36 — when the app declares
// scheduled cron jobs, AUTH_SERVICE_TOKEN is deploy-required (the compose fails the deploy without it), so
// it belongs on the checklist even if it wasn't separately declared.
function neededSecretNames(opts: ProvisioningRunbookOptions): string[] {
  const names = ['FORGE_SECRETS_KEY'];
  if (opts.withPostgres) names.push('POSTGRES_PASSWORD');
  for (const s of opts.secrets) if (!names.includes(s)) names.push(s);
  if (opts.withJobs && !names.includes('AUTH_SERVICE_TOKEN')) names.push('AUTH_SERVICE_TOKEN');
  return names;
}

export function generateProvisioningRunbook(opts: ProvisioningRunbookOptions): string {
  const needed = neededSecretNames(opts);
  const declared = new Set(opts.secrets);
  const usesAuth = declared.has(AUTH_SESSION_SECRET_NAME);
  const hasGoogle = GOOGLE_SECRET_NAMES.every((n) => declared.has(n));
  const hasEmail = EMAIL_SECRET_NAMES.every((n) => declared.has(n));

  const out: string[] = [];
  out.push(`# Provisioning — ${opts.appName}`);
  out.push('');
  out.push('> Generated by Forge — Productionize. Do not hand-edit; re-run `forge productionize` instead.');
  out.push('> It lists exactly the secrets **this** app needs (a subset of the full matrix in `forge/PROVISIONING.md`).');
  out.push('');
  out.push(`Public host: \`${opts.host}\`. Real values live in \`app/.env.prod\` (never committed) — this file only explains them.`);
  out.push('');

  // Checklist table.
  out.push('## What this app needs');
  out.push('');
  out.push('| Secret | Capability | Requirement | What it is |');
  out.push('|---|---|---|---|');
  for (const name of needed) {
    const spec = describeSecret(name);
    out.push(`| \`${name}\` | ${spec.capability} | ${requirementLabel(spec)} | ${spec.what} |`);
  }
  out.push('');

  // Per-secret detail.
  out.push('## Set each value');
  out.push('');
  for (const name of needed) {
    const spec = describeSecret(name);
    out.push(`### \`${name}\` — ${requirementLabel(spec)}`);
    out.push('');
    out.push(`- **Capability:** ${spec.capability}`);
    out.push(`- **What:** ${spec.what}`);
    out.push(`- **When needed:** ${spec.requires_note}`);
    out.push(`- **Obtain:** ${spec.obtain}`);
    if (spec.generate) out.push(`- **Generate:** \`${spec.generate}\``);
    out.push(...setCommandLines(opts.appName, name));
    out.push('');
  }

  // The reported gap: with neither Google nor SMTP, there is NO working signup path.
  if (usesAuth) {
    out.push('## Enabling a working sign-in method (C10)');
    out.push('');
    out.push('This app uses hosted auth (C10). **A user needs at least one working sign-in method.** With *neither* Google OAuth *nor* SMTP configured, `/auth/signup` shows **no form** and reports that email sign-up is unavailable — there is **no way to sign in**. Configure at least one:');
    out.push('');
    out.push(`- **Google sign-in** — set \`GOOGLE_CLIENT_ID\` + \`GOOGLE_CLIENT_SECRET\`. Works with **no email dependency**. Authorized redirect URI: \`https://${opts.host}/auth/google/callback\`.${hasGoogle ? ' _(declared as a secret)_' : ' _(wired into the data-plane — just fill `.env.prod`)_'}`);
    out.push(`- **Email + password** — set \`SMTP_URL\` + \`EMAIL_FROM\`. Unlocks email/password **signup + verification + password reset**.${hasEmail ? ' _(declared as a secret)_' : ' _(wired into the data-plane — just fill `.env.prod`)_'}`);
    out.push('');
    // P34 — productionize now wires the optional Google/SMTP vars into the data-plane automatically when the
    // app uses hosted auth, so `.env.prod` is the single source of truth: fill a value and redeploy — NO
    // `--secret` re-declare / re-productionize needed.
    if (!hasGoogle || !hasEmail) {
      out.push('These optional provider vars are already wired into the data-plane (P34) — you do **not** need to re-declare them. Just add the value(s) to `app/.env.prod` and redeploy:');
      out.push('');
      out.push('```sh');
      out.push(`# edit app/.env.prod — e.g. GOOGLE_CLIENT_ID=…  GOOGLE_CLIENT_SECRET=…  (and/or SMTP_URL=…  EMAIL_FROM=…)`);
      out.push(`./forge deploy --app ${opts.appName}`);
      out.push('```');
      out.push('');
    }
  }

  if (opts.withJobs) {
    out.push('## Scheduled jobs (C2) + the cron service token (P36)');
    out.push('');
    out.push(`\`${JOBS_FILE}\` is mounted into the data-plane sidecar and registered on boot — no env needed.`);
    out.push('');
    out.push('**The cron fire is authenticated.** The C2 scheduler calls each job back at `POST /api/cron/*` presenting `AUTH_SERVICE_TOKEN` as **both** an `Authorization: Bearer <token>` header **and** an `x-forge-service-token: <token>` header. Because Traefik routes all `/api/*` **publicly**, the app **must** gate `/api/cron/*` on this token (constant-time compare) — otherwise the endpoints are open. `productionize` makes `AUTH_SERVICE_TOKEN` **deploy-required** whenever jobs are declared, so a missing token **fails the deploy** rather than silently firing unauthenticated. Set it in `app/.env.prod` (`openssl rand -hex 32`).');
    out.push('');
  }

  return out.join('\n');
}
