#!/usr/bin/env bash
# Forge runner startup script — generated by templatefile(); edit startup.sh.tpl, not this.
set -euo pipefail

# --- CI toolchain (idempotent) ---
# setup-terraform needs unzip; npm ci needs system node; forge CLI needs Node 22.
if ! command -v node >/dev/null || ! command -v unzip >/dev/null; then
  apt-get update -y
  apt-get install -y docker.io jq curl unzip git ca-certificates python3
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y nodejs
  systemctl enable --now docker
fi
useradd -m runner 2>/dev/null || true
usermod -aG docker runner

# --- Runner-liveness health probe ---
# A small HTTP server on :${health_check_port} queried by the GCP MIG health check.
# Returns 200 OK when the runner service is active, registered, and heartbeating.
# Returns 503 when the service has stopped, the runner is deregistered, or logs have
# not been updated for more than ${idle_threshold_minutes} minutes (idle-stuck signal).
#
# Idle-stuck tuning: the runner pings GitHub every ~50 s and writes Runner_*.log on
# each attempt — including connection-error retries during a GitHub-side outage.  That
# means the log stays fresh during a GitHub outage, so autohealing does NOT fire while
# GitHub is merely unavailable.  Only a genuinely hung process (not writing at all) will
# let the log go stale and trip the ${idle_threshold_minutes}-minute threshold.
cat > /usr/local/bin/runner-health-probe << 'PYEOF'
#!/usr/bin/env python3
"""
Runner liveness probe.
Listens on :${health_check_port}/health and is queried by the GCP MIG health check.
Returns 200 OK  — runner service active, registered, heartbeating.
Returns 503 503 — service down, not registered, or idle-stuck (logs stale).
"""
import glob, http.server, logging, os, pathlib, subprocess, time

RUNNER_HOME    = "/home/runner/actions-runner"
IDLE_THRESHOLD = int(os.environ.get("IDLE_THRESHOLD_MINUTES", "${idle_threshold_minutes}")) * 60
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")


def _check() -> list[str]:
    """Return a list of failure reasons; empty list = healthy."""
    reasons: list[str] = []

    # 1. Runner systemd service is active.
    try:
        out = subprocess.check_output(
            ["systemctl", "list-units", "--no-legend", "--state=active", "actions.runner.*"],
            stderr=subprocess.DEVNULL, text=True,
        ).strip()
        if not out:
            reasons.append("runner service not active (systemctl shows no active actions.runner.* unit)")
    except Exception as exc:
        reasons.append(f"systemctl query failed: {exc}")

    # 2. .runner config file exists (proves successful GitHub registration).
    if not (pathlib.Path(RUNNER_HOME) / ".runner").exists():
        reasons.append(f".runner config missing at {RUNNER_HOME}/.runner — not registered")

    # 3. Heartbeat: any _diag/*.log file (Runner or Worker) updated within the threshold.
    #    If no log files exist yet (freshly started service), treat as healthy — the
    #    initial_delay_sec grace window covers the gap between service start and first log.
    logs = glob.glob(f"{RUNNER_HOME}/_diag/*.log")
    if logs:
        latest_mtime = max(os.path.getmtime(f) for f in logs)
        age_sec = time.time() - latest_mtime
        if age_sec > IDLE_THRESHOLD:
            reasons.append(
                f"runner logs stale for {int(age_sec / 60)} min "
                f"(threshold ${idle_threshold_minutes} min) — idle-stuck?"
            )

    return reasons


class _Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self) -> None:
        if self.path not in ("/health", "/"):
            self.send_response(404); self.end_headers(); return
        reasons = _check()
        body = ("UNHEALTHY: " + "; ".join(reasons) if reasons else "OK").encode()
        self.send_response(503 if reasons else 200)
        self.send_header("Content-Type", "text/plain")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *_: object) -> None:
        pass  # silence per-request access log to avoid journald noise


if __name__ == "__main__":
    port = int(os.environ.get("HEALTH_PORT", "${health_check_port}"))
    logging.info("runner-health-probe listening on :%d (idle threshold: %dm)", port, ${idle_threshold_minutes})
    http.server.HTTPServer(("", port), _Handler).serve_forever()
PYEOF
chmod +x /usr/local/bin/runner-health-probe

# --- Systemd unit for the liveness probe ---
cat > /etc/systemd/system/runner-health-probe.service << 'UNITEOF'
[Unit]
Description=GitHub Actions runner liveness probe (:${health_check_port}/health)
Documentation=https://github.com/mardash-ai/forge/blob/main/terraform/modules/runner/RUNBOOK.md
After=network.target

[Service]
Type=simple
Environment=IDLE_THRESHOLD_MINUTES=${idle_threshold_minutes}
Environment=HEALTH_PORT=${health_check_port}
ExecStart=/usr/bin/python3 /usr/local/bin/runner-health-probe
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
UNITEOF

systemctl daemon-reload
systemctl enable --now runner-health-probe

# --- GitHub Actions runner install and registration ---
cd /home/runner
if [ ! -d actions-runner ]; then
  mkdir actions-runner && cd actions-runner
  curl -sL "https://github.com/actions/runner/releases/download/v${runner_version}/actions-runner-linux-x64-${runner_version}.tar.gz" | tar xz
  chown -R runner:runner /home/runner/actions-runner
else
  cd actions-runner
fi

PAT="$(gcloud secrets versions access latest --secret=github-runner-pat --project=${project_id})"
# Org-level registration token (short-lived; the PAT never touches the runner config file).
TOKEN="$(curl -s -X POST -H "Authorization: Bearer $PAT" \
  "https://api.github.com/orgs/${github_owner}/actions/runners/registration-token" | jq -r .token)"

sudo -u runner ./config.sh --unattended --replace \
  --url "https://github.com/${github_owner}" \
  --token "$TOKEN" \
  --name "$(hostname)" \
  --labels "gcp,self-hosted,linux,x64" || true

./svc.sh install runner || true
./svc.sh start
